# Generated by Django 5.1.3 on 2024-11-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_date_appointment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_time',
            new_name='dateTime',
        ),
    ]
